import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { Navbar } from "@/components/Navbar";

export const metadata: Metadata = {
  title: {
    default: "Prefyne – Refine AI Prompts Instantly",
    template: "%s | Prefyne",
  },
  description:
    "Prefyne helps you turn rough ideas into clear, powerful AI prompts. Built for developers, creators, and students.",
  keywords: [
    "AI prompt refinement",
    "prompt engineering",
    "AI prompts",
    "AI tools",
    "ChatGPT prompts",
    "Gemini prompts",
    "developer tools",
    "creator tools",
    "student tools",
    "productivity",
    "AI assistance",
    "prompt optimization",
    "Prefyne",
    "AI prompt generator",
    "refine AI prompts",
    "improve AI prompts",
    "AI prompt enhancer",
    "next-gen AI prompts",
    "AI prompt solutions",
    "AI prompt platform",
    "AI prompt app",
    "AI prompt service",
    "AI prompt software",
    "AI prompt technology",
    "AI prompt innovation",
    "AI prompt development",
    "AI prompt management",
    "AI prompt customization",
    "AI prompt integration",
    "AI prompt analytics",
    "AI prompt performance",
    "AI prompt feedback",
    "AI prompt collaboration",
    "AI prompt community",
    "AI prompt resources",
    "AI prompt tutorials",
    "AI prompt support",
    "AI prompt updates",
    "AI prompt news",
    "AI prompt trends",
    "AI prompt insights",
    "AI prompt strategies",
    "AI prompt best practices",
    "AI prompt case studies",
    "AI prompt success stories",
    "AI prompt tips",
    "AI prompt tricks",
    "AI prompt hacks",
    "AI prompt guides",
    "AI prompt workshops",
    "AI prompt webinars",
    "AI prompt events",
    "AI prompt conferences",
    "AI prompt meetups",
    "AI prompt networking",
    "AI prompt collaboration tools",
    "AI prompt project management",
    "AI prompt version control",
    "AI prompt documentation",
    "AI prompt knowledge base",
    "AI prompt FAQs",
    "AI prompt user forums",
    "AI prompt social media",
    "AI prompt blogs",
    "AI prompt newsletters",
    "AI prompt podcasts",
    "AI prompt videos",
    "AI prompt demos",
    "AI prompt trials",
    "AI prompt subscriptions",
    "AI prompt pricing",
    "AI prompt plans",
    "AI prompt features",
    "AI prompt benefits",
    "AI prompt value",
    "AI prompt ROI",
    "AI prompt case studies",
    "AI prompt testimonials",
    "AI prompt reviews",
    "AI prompt ratings",
    "AI prompt comparisons",
    "AI prompt alternatives",
    "AI prompt competitors",
    "AI prompt market",
    "AI prompt industry",
    "AI prompt trends",
    "AI prompt future",
    "AI prompt innovation",
    "AI prompt disruption",
    "AI prompt transformation",
    "AI prompt evolution",
    "AI prompt revolution",
    "AI prompt impact",
    "AI prompt change",
    "AI prompt growth",
    "AI prompt success",
    "AI prompt leadership",
    "AI prompt vision",
    "AI prompt mission",
    "AI prompt values",
    "AI prompt culture",
    "AI prompt team",
    "AI prompt careers",
    "AI prompt jobs",
    "AI prompt hiring",
    "AI prompt internships",
    "AI prompt partnerships",
    "AI prompt collaborations",
    "AI prompt sponsorships",
    "AI prompt affiliations",
    "AI prompt alliances",
    "AI prompt networks",
    "AI prompt ecosystems",
    "AI prompt communities",
    "AI prompt societies",
    "AI prompt organizations",
    "AI prompt associations",
    "Prefyne AI",
    "Prefyne prompts",
    "Prefyne app",
    "Prefyne platform",
    "Prefyne service",
    "Prefyne software",
    "Prefyne technology",
    "Prefyne innovation",
    "Prefyne development",
    "Prefyne management",
    "Prefyne customization",
    "Prefyne integration",
    "Prefyne analytics",
    "Prefyne performance",
    "Prefyne feedback",
    "Prefyne collaboration",
    "Prefyne community",
    "Prefyne resources",
    "Prefyne tutorials",
    "Prefyne support",
    "Prefyne updates",
    "Prefyne news",
    "Prefyne trends",
    "Prefyne insights",
    "Prefyne strategies",
    "Prefyne best practices",
    "Prefyne case studies",
    "Prefyne success stories",
    "Prefyne tips",
    "Prefyne tricks",
    "Prefyne hacks",
    "Prefyne guides",
    "Prefyne workshops",
    "Prefyne  webinars",
    "Prefyne events",
    "Prefyne conferences",
    "Prefyne meetups",
    "Prefyne networking",
    "Prefyne collaboration tools",
    "Prefyne project management",
    "Prefyne version control",
    "Prefyne documentation",
    "Prefyne knowledge base",
    "Prefyne FAQs",
    "Prefyne user forums",
    "Prefyne social media",
  ],
  authors: [{ name: "Avatar" }],
  openGraph: {
    title: "Prefyne – Prompt Engineering Made Simple",
    description:
      "Turn raw ideas into high-quality AI prompts with Prefyne.",
    url: "https://prefyne.vercel.app",
    siteName: "Prefyne",
    images: [
      {
        url: "/og.png",
        width: 1200,
        height: 630,
        alt: "Prefyne – AI Prompt Refinement Tool",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Prefyne – Refine AI Prompts Instantly",
    description:
      "From rough thoughts to refined AI prompts in seconds.",
    images: ["/og.png"],
  },

  creator: "Prefyne",
  metadataBase: new URL("https://prefyne.vercel.app"),
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="relative min-h-screen mx-auto text-foreground">
        <Providers>
          <div className="relative min-h-screen">
            <div className="fixed inset-0 -z-10 bg-container" />
            <div className="fixed inset-0 -z-10 bg-overlay" />
            <Navbar />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
